[toolchain]

[features]
resolution = true
skip-lint = false



[programs.devnet]
pump_science = "HrxD6G1BXH4Sc1mhNxegse5rh1ZjMcetxWTGM5DfRAhZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./test_key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"