[toolchain]

[features]
resolution = true
skip-lint = false



[programs.localnet]
pump_science = "4HNtUwX2P8z275jK3R6x7KoFqPx3bQWjXxhWtAFCiuvW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./pump_key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"