[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_science = "EtZR9gh25YUM6LkL2o2yYV1KzyuDdftHvYk3wsb2Ypkj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
